global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:3000']

  - job_name: 'antifraud-service'
    static_configs:
      - targets: ['antifraud-service:3000']
